name: Sandracare
favicon: null
layout_spectrum: 0.6924949842505157
typography_spectrum: 0.7940818949136883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2254199597518891
  lightness: 0.5066464941482991
  saturation: 0.737467099679634
  rhythmicContrast: 0.49405854754149914
purpose: []
