name: Sandracare
favicon: null
layout_spectrum: 0.6924949842505157
typography_spectrum: 0.82888
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060908'
    - '#c4c8d1'
    - '#a1968c'
    - '#5b5c60'
    - '#0091bc'
  brandStrength: 0.3125
  lightness: 0.5066464941482991
  saturation: 0.737467099679634
  rhythmicContrast: 0.49405854754149914
purpose: []
